import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Proadvisor",
  description: "Generated by create next app",
};

export default function RootLayout({ children, openNavbar }) {
  // const test = false;
  // const openNavbar = false
  console.log("Opennavbar boolean: ", openNavbar)
  return (
    <html lang="en" className="box-border">
      <body className="flex flex-col min-h-screen">
        {openNavbar && <Header className="" />}

        <main className="flex-1">{children}</main>

        {openNavbar && <Footer className="" />}
      </body>
    </html>
  );
}
