import LandingPage from "./landingPage/page";

// export const metadata = {
//   title: "Proadvisor",
//   description: "Generated by create next app",
// };

export default function Home() {
  return (
    <>
      {/* <head>
        <title>Proadvisor</title>
        <meta name="description" content="Generated by create next app" />
      </head> */}
      <main className="flex flex-col items-center justify-between">
        {/* <TestPage /> */}
        <LandingPage />
      </main>
    </>
  );
}
